WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11851cdbd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1eb612fb-6b1a-4728-8f44-cf117aa2bb7a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11851cdd90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1eb612fb-6b1a-4728-8f44-cf117aa2bb7a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f11851cd590>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/1eb612fb-6b1a-4728-8f44-cf117aa2bb7a/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fa31450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3fc69d9f-fdd7-4e94-bac6-8dbd5a05a290/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fa61ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3fc69d9f-fdd7-4e94-bac6-8dbd5a05a290/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f117fa63750>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/3fc69d9f-fdd7-4e94-bac6-8dbd5a05a290/screenshot