WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39c84c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9f5448a-7d8a-4699-a6d5-1e437dfbac40/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39c86610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9f5448a-7d8a-4699-a6d5-1e437dfbac40/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39c84910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/a9f5448a-7d8a-4699-a6d5-1e437dfbac40/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b53650>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/00e5c6fc-9508-4eb8-a1f8-b6dce6f533f6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b68610>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/00e5c6fc-9508-4eb8-a1f8-b6dce6f533f6/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3996d690>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/00e5c6fc-9508-4eb8-a1f8-b6dce6f533f6/screenshot