WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a2f5de50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8917b502-ea6d-413e-b1d6-682d7c288eb1/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a2fca990>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8917b502-ea6d-413e-b1d6-682d7c288eb1/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a2fca890>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/8917b502-ea6d-413e-b1d6-682d7c288eb1/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1ae9c10>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/458b8548-b2e8-487d-b803-682b2088c358/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1cbfb50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/458b8548-b2e8-487d-b803-682b2088c358/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb5a1cbfa50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/458b8548-b2e8-487d-b803-682b2088c358/screenshot