WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b527d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/0cfa9912-3a42-4e69-85ca-d015c8e56834/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b50050>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/0cfa9912-3a42-4e69-85ca-d015c8e56834/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39b6b090>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/0cfa9912-3a42-4e69-85ca-d015c8e56834/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39708550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d2acd30a-ed09-4308-acab-b8edf511876e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f3970b210>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d2acd30a-ed09-4308-acab-b8edf511876e/screenshot
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f39944a50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/d2acd30a-ed09-4308-acab-b8edf511876e/screenshot